# Tool aliases
alias c="clear"
alias q="exit"
alias cat="bat"
alias top="btop"
alias ls="lsd"
alias cd="z"
# alias sed="sd"
alias ps="procs"
alias man="batman"
# alias find="fd"
alias ollama-start="brew services start ollama"
alias ollama-stop="brew services stop ollama"

# Development aliases
alias python="python3"
alias npm="npmc"
alias pnpm="npmc --pnpm-alias"
alias bun="npmc --bun-alias"
alias code="codium"