# Tool aliases
alias c="clear"
alias q="exit"
alias cat="bat"
alias top="btop"
alias ls="lsd"
alias cd="z"
# alias sed="sd"
alias ps="procs"
alias man="batman"
# alias find="fd"
alias ollama-start="brew services start ollama"
alias ollama-stop="brew services stop ollama"
alias pdi="sdk use java 17.0.2-open && /Applications/data-integration/spoon.sh"

# Development aliases
alias gcc="gcc-13"
alias g++="g++-13"
alias python="python3"
alias npm="npmc"
alias pnpm="npmc --pnpm-alias"
alias bun="npmc --bun-alias"
