tap "charmbracelet/tap"
tap "ggozad/formulas"
tap "homebrew/bundle"
tap "homebrew/services"
tap "jorgerojas26/lazysql"
tap "kaplanelad/tap"
tap "lihaoyun6/tap"
tap "oven-sh/bun"
tap "sdkman/tap"
brew "ack"
brew "actionlint"
brew "age"
brew "antidote"
brew "xz"
brew "bat"
brew "bat-extras"
brew "bitwarden-cli"
brew "btop"
brew "chezmoi"
brew "cmake"
brew "coreutils"
brew "ctop"
brew "curl"
brew "docker"
brew "fastfetch"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-extras"
brew "gitleaks"
brew "readline"
brew "gum"
brew "sqlite"
brew "httpie"
brew "imagemagick"
brew "kondo"
brew "lazydocker"
brew "lazygit"
brew "lsd"
brew "markdownlint-cli2"
brew "mas"
brew "navi"
brew "neovim"
brew "nvm"
brew "ollama", restart_service: :changed
brew "pkgconf"
brew "poppler"
brew "procs"
brew "ripgrep"
brew "rmlint"
brew "sd"
brew "sevenzip"
brew "sshs"
brew "starship"
brew "switchaudio-osx"
brew "tcl-tk@8"
brew "tealdeer"
brew "thefuck"
brew "tmux"
brew "topgrade"
brew "tree"
brew "trivy"
brew "uv"
brew "wget"
brew "yamllint"
brew "yazi"
brew "yq"
brew "zoxide"
brew "charmbracelet/tap/freeze"
brew "ggozad/formulas/oterm"
brew "jorgerojas26/lazysql/lazysql"
brew "kaplanelad/tap/shellfirm"
brew "sdkman/tap/sdkman-cli"
cask "adguard"
cask "affinity-designer"
cask "affinity-photo"
cask "affinity-publisher"
cask "airbattery"
cask "android-platform-tools"
cask "appcleaner"
cask "balenaetcher"
cask "bartender"
cask "bruno"
cask "chatgpt"
cask "daisydisk"
cask "dash@6"
cask "datagrip"
cask "deepl"
cask "devtoys"
cask "downie"
cask "drawio"
cask "fantastical"
cask "figma"
cask "firefox@developer-edition"
cask "font-jetbrains-mono-nerd-font"
cask "ghostty"
cask "github-copilot-for-xcode"
cask "gitify"
cask "imazing"
cask "intellij-idea"
cask "istat-menus"
cask "keka"
cask "languagetool-desktop"
cask "legcord"
cask "little-snitch"
cask "lookaway"
cask "lunar"
cask "mac-mouse-fix"
cask "mactex-no-gui"
cask "macupdater"
cask "melodics"
cask "mixed-in-key"
cask "msty"
cask "native-access"
cask "network-radar"
cask "obsidian"
cask "onyx"
cask "orbstack"
cask "pdf-expert"
cask "permute"
cask "pycharm"
cask "raspberry-pi-imager"
cask "raycast"
cask "rekordbox"
cask "sf-symbols"
cask "synology-drive"
cask "synology-image-assistant"
cask "teamviewer"
cask "tex-live-utility"
cask "texifier"
cask "timemachineeditor"
cask "typeface"
cask "typora"
cask "ungoogled-chromium"
cask "vmware-fusion"
cask "vscodium"
cask "webstorm"
cask "whatsapp"
cask "yubico-authenticator"
cask "zotero"
mas "AusweisApp", id: 948660805
mas "Bitwarden", id: 1352778147
mas "Cascadea", id: 1432182561
mas "Compressor", id: 424390742
mas "Cursor Pro", id: 1447043133
mas "DaftCloud", id: 1320450034
mas "eduVPN", id: 1317704208
mas "Endel", id: 1346247457
mas "Final Cut Pro", id: 424389933
mas "Gestimer", id: 6447125648
mas "Keystroke Pro", id: 1572206224
mas "Klack", id: 6446206067
mas "LanguageTool", id: 1534275760
mas "Logic Pro", id: 634148309
mas "Lumaly", id: 1573979983
mas "Mirror Magnet", id: 1563698880
mas "Motion", id: 434290957
mas "Noir", id: 1592917505
mas "Octotree", id: 1457450145
mas "Reeder", id: 1529448980
mas "Refined GitHub", id: 1519867270
mas "SnippetsLab", id: 1006087419
mas "Stecker", id: 6447288587
mas "Streaks", id: 963034692
mas "Structured", id: 1499198946
mas "Swift Playground", id: 1496833156
mas "Things", id: 904280696
mas "UnTrap", id: 1637438059
mas "VPN Unlimited®", id: 694633015
mas "WaterMinder", id: 1415257369
mas "Xcode", id: 497799835
vscode "42crunch.vscode-openapi"
vscode "alefragnani.project-manager"
vscode "ban.spellright"
vscode "catppuccin.catppuccin-vsc"
vscode "catppuccin.catppuccin-vsc-icons"
vscode "continue.continue"
vscode "deerawan.vscode-faker"
vscode "formulahendry.auto-close-tag"
vscode "formulahendry.auto-complete-tag"
vscode "formulahendry.auto-rename-tag"
vscode "gruntfuggly.bettercomment"
vscode "mikestead.dotenv"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "oderwat.indent-rainbow"
vscode "redhat.vscode-yaml"
vscode "seatonjiang.gitmoji-vscode"
vscode "shardulm94.trailing-spaces"
vscode "streetsidesoftware.code-spell-checker"
vscode "vivaxy.vscode-conventional-commits"
